FROM docker.elastic.co/kibana/kibana-oss:6.2.4

RUN /usr/share/kibana/bin/kibana-plugin install 'https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/6.2.4/raw/artifact/elastalert-kibana-plugin-latest.zip?job=build'

#EXPOSE 5601

#CMD ["/usr/local/bin/kibana-docker"]
