apiVersion: v1
kind: ReplicationController
metadata: 
  name: samba
  namespace: oa
  labels: 
    name: samba
spec: 
  replicas: 1
  template: 
    metadata: 
      name: samba
      labels: 
        name: samba
    spec: 
      containers: 
        - name: samba
          image: dperson/samba
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 137
            - containerPort: 138
            - containerPort: 139
            - containerPort: 445
          volumeMounts: 
            - name: samba
              mountPath: /root
      volumes: 
        - name: samba
          hostPath:
            path: /root/allShare
---
apiVersion: v1
kind: Service
metadata: 
    name: samba
    namespace: oa
    labels:
       name: samba
spec: 
    type: NodePort
    ports: 
      - name: p1
        port: 137
        targetPort: 137
        nodePort: 137
      - name: p2
        port: 138
        targetPort: 138
        nodePort: 138
      - name: p3
        port: 139
        targetPort: 139
        nodePort: 139
      - name: p4
        port: 445
        targetPort: 445
        nodePort: 445
    selector: 
        name: samba