apiVersion: v1
kind: ConfigMap
metadata:
  name: elastalert-configmap
data:
  elastalert_config.yaml: |-
    # 定义规则目录
    rules_folder: /opt/rules
    scan_subdirectories: false
    # 定义查询ES时间间隔，秒~周
    run_every:
      minutes: 1
    # 缓存最近结果的时间周期
    buffer_time:
      minutes: 15
    # ES相关信息
    es_host: ${ES_HOST}
    es_port: ${ES_PORT}
    es_username: ${ES_USERNAME}
    es_password: ${ES_PASSWORD}
    # 定义用来ES中用来存储elastalert元数据的索引
    writeback_index: elastalert_status
    # 如果发送警报失败，其会在下面这段时间内重试
    alert_time_limit:
      days: 2
  smtp_auth_file.yaml: |-
    user: ***@163.com
    # POP3密码
    password: ***
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastalert-rules-configmap
data:
  email_frequency.yaml: |-
    # 可选
    #es_host: ${ES_HOST}
    #es_port: ${ES_PORT}
    #es_username: ${ES_USERNAME}
    #es_password: ${ES_PASSWORD}

    # 唯一的规则名
    name: Test frequency rule
    # 规则类型，frequency对应num_events
    type: frequency
    # 监控的es数据索引
    index: logstash-*
    # 当设置的报警规则触发2次后执行报警
    num_events: 2
    # num_events必须在这段时间内触发报警
    timeframe:
      # 触发报警有效期为1分钟内，可以定义hours等
      minutes: 1
    # 配置过滤器，ES的query-dsl语法
    filter:
    - query:
        query_string:
          query: "hostIP: 10.42.1.88"
    
    # 5分钟内，当ID不同时，会被当作不同的报警处理
    query_key:
      - monitor.id
    realert:
      minutes: 5

    # 当发生匹配时报警类型
    alert:
    - "email"

    # 接收报警的地址列表
    email:
    - "***@163.com"

    # 发送邮箱相关设置
    smtp_host: "smtp.163.com"
    smtp_port: 25
    smtp_auth_file: "/opt/config/smtp_auth_file.yaml"
    email_reply_to: "***@163.com"
    from_addr: "***@163.com"
    cc: "***@163.com"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elastalert
  labels:
    k8s-app: elastalert
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: elastalert
    spec:
      containers:
      - name: elastalert
        image: jertel/elastalert-docker
        imagePullPolicy: Always
        env:
        - name: ES_HOST
          value: elasticsearch
        - name: ES_PORT
          value: "9200"
        - name: ES_USERNAME
          value: elastic
        - name: ES_PASSWORD
          value: changeme
        volumeMounts:
        - name: config
          mountPath: /opt/config
        - name: rules
          mountPath: /opt/rules
      volumes:
      - name: config
        configMap:
          name: elastalert-configmap
      - name: rules
        configMap:
          name: elastalert-rules-configmap
