apiVersion: v1
kind: ReplicationController
metadata: 
  name: svn
  labels: 
    name: svn
spec: 
  replicas: 1
  template: 
    metadata: 
      name: svn
      labels: 
        name: svn
    spec:
      containers: 
        - name: svn
          image: svn-server 
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 22
            - containerPort: 80
          volumeMounts: 
            - name: svnpath
              mountPath: /svn
      volumes: 
        - name: svnpath
          nfs:
            server: 172.18.26.11
            path: /root/shareData/svn
---
apiVersion: v1
kind: Service
metadata: 
    name: svn
    labels:
       name: svn
spec: 
    type: NodePort
    ports: 
      - name: http
        port: 80
        targetPort: 80
        nodePort: 8090
      - name: ssh
        port: 22
        targetPort: 22
        targetPort: 8022
    selector: 
        name: svn