apiVersion: v1
kind: ReplicationController
metadata: 
  name: gitlab-ce
  labels: 
    name: gitlab-ce
spec: 
  replicas: 1
  template: 
    metadata: 
      name: gitlab-ce
      labels: 
        name: gitlab-ce
    spec: 
      containers: 
        - name: gitlab-ce
          image: gitlab/gitlab-ce:9.1.3-ce.0
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 80
          env: 
            - name: GITLAB_OMNIBUS_CONFIG
              value: "external_url 'http://172.18.24.201';registry_external_url 'https://172.18.24.201:5000' "
          volumeMounts: 
            - name: gitlab-config
              mountPath: /etc/gitlab
            - name: gitlab-logs
              mountPath: /var/log/gitlab
            - name: gitlab-data
              mountPath: /var/opt/gitlab
      volumes: 
        - name: gitlab-config
          hostPath:
            path: /root/hakugei-local/gitlab-ce/conf
        - name: gitlab-logs
          hostPath:
            path: /root/hakugei-local/gitlab-ce/logs
        - name: gitlab-data
          hostPath:
            path: /root/hakugei-local/gitlab-ce/data
# mkdir -p gitlab-ce/conf gitlab-ce/logs gitlab-ce/data && chmod -R 777 gitlab-ce
---
apiVersion: v1
kind: Service
metadata: 
    name: gitlab-ce
    labels:
       name: gitlab-ce
spec: 
    type: NodePort
    ports: 
      - port: 80
        targetPort: 80
        nodePort: 10080
    selector: 
        name: gitlab-ce

        