apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-beat-multi
  labels:
    app-beat: app-beat-multi
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app-beat: app-beat-multi
    spec:
      terminationGracePeriodSeconds: 30
#      hostNetwork: true	# 使用主机网络模式
#      dnsPolicy: ClusterFirstWithHostNet	# 使用k8s的dns
      containers:
      - name: spring-boot-filebeat
        image: 172.18.3.108/ebk/spring-boot-filebeat:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8666
        volumeMounts:
        - name: shared-log
          mountPath: /logs
        - name: timezone
          mountPath: /etc/localtime
        - name: data
          mountPath: /usr/share/filebeat/data

      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.3.0
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        securityContext:
          runAsUser: 0
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: changeme
        - name: KIBANA_HOST
          value: kibana
        - name: KIBANA_PORT
          value: "5601"
        volumeMounts:
        - name: shared-log
          mountPath: /logs
        - name: timezone
          mountPath: /etc/localtime
        - name: filebeat-config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: filebeat-data
          mountPath: /usr/share/filebeat/data

      - name: packetbeat
        image: docker.elastic.co/beats/packetbeat:6.3.0
        args: [
          "-c", "/etc/packetbeat.yml",
          "-e",
        ]
        # 开启权限监测主机网络
        securityContext:
          runAsUser: 0
          #capabilities:
            #add:
            #- NET_ADMIN
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: changeme
        - name: KIBANA_HOST
          value: kibana
        - name: KIBANA_PORT
          value: "5601"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: packetbeat-config
          mountPath: /etc/packetbeat.yml
          readOnly: true
          subPath: packetbeat.yml
        - name: packetbeat-data
          mountPath: /usr/share/packetbeat/data

      volumes:
      - name: shared-log
        emptyDir: {}
      - name: timezone
        hostPath:
          path: /etc/localtime
      - name: filebeat-data
        hostPath:
          path: /ebk/filebeat/data
      - name: packetbeat-data
        hostPath:
          path: /ebk/packetbeat/data
      - name: filebeat-config
        configMap:
          name: filebeat-configmap
      - name: packetbeat-config
        configMap:
          name: packetbeat-multi-configmap