apiVersion: v1
kind: ReplicationController
metadata: 
  name: squid3
  namespace: kube-system
  labels: 
    name: squid3
spec: 
  replicas: 3
  template: 
    metadata: 
      name: squid3
      labels: 
        name: squid3
    spec: 
      containers: 
        - name: squid3
          image: sameersbn/squid:3.3.8-20
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 3128
---
apiVersion: v1
kind: Service
metadata: 
    name: squid3
    namespace: kube-system
    labels:
       name: squid3
spec: 
    type: NodePort
    ports: 
      - port: 3128
        targetPort: 3128
        nodePort: 3128
    selector: 
        name: squid3