apiVersion: v1
kind: PersistentVolume
metadata: 
  name: gluster-pv
spec: 
  capacity: 
    storage: 2Gi 
  accessModes: 
    - ReadWriteMany
  glusterfs: 
    endpoints: glusterfs-cluster 
    path: k8s-conf
    readOnly: false